language: python
python:
  - '3.8'
  - '3.6' # Keep in sync with setup.py
cache: pip
env:
  - REQS=requirements.txt
  - REQS=requirements-lower-bound.txt
script:
  - pip install -r $REQS
  - pip install -r requirements-dev.txt
  - ./test.sh
